# -*- coding: utf-8 -*-
"""German Credit Risk

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cqD7sKXUU4Z2EMhxfGbRWIpBTpMZvKFJ
"""

!ls /content/

df = pd.read_csv('/content/data.csv')
df.head()

import os
print(os.listdir('/content/'))

import pandas as pd

df = pd.read_csv('/content/mydata.csv')
df.head()

!ls /content/

# Get basic info about columns, types, and non-null counts
df.info()

# Summary statistics for numeric columns
df.describe()

df.isnull().sum()

print(df['Saving accounts'].unique())
print(df['Checking account'].unique())
print(df['Saving accounts'].dtype)
print(df['Checking account'].dtype)

df['Saving accounts'].fillna('Unknown', inplace=True)
df['Checking account'].fillna('Unknown', inplace=True)

df.isnull().sum()

# For example, if you have a column 'Gender'
df['Sex'].value_counts()

import seaborn as sns
import matplotlib.pyplot as plt

# Distribution of a numerical column
sns.histplot(df['Age'])
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8,5))
sns.histplot(df['Age'], bins=30, kde=True)
plt.title('Age Distribution')
plt.show()

plt.figure(figsize=(6,4))
sns.countplot(x='Sex', data=df)
plt.title('Count of Sex Categories')
plt.show()

plt.figure(figsize=(8,5))
sns.boxplot(x='Housing', y='Credit amount', data=df)
plt.title('Credit Amount by Housing Type')
plt.show()

plt.figure(figsize=(10,7))
# Select only numerical columns for correlation calculation
numerical_df = df.select_dtypes(include=['number'])
sns.heatmap(numerical_df.corr(), annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()

df['Purpose'].value_counts().plot.pie(autopct='%1.1f%%', figsize=(7,7))
plt.title('Purpose Distribution')
plt.ylabel('')
plt.show()

plt.figure(figsize=(8,5))
sns.scatterplot(x='Duration', y='Credit amount', hue='Sex', data=df)
plt.title('Duration vs Credit Amount by Sex')
plt.show()

sns.pairplot(df[['Age', 'Credit amount', 'Duration', 'Job']], diag_kind='kde')
plt.show()

plt.figure(figsize=(8,5))
sns.barplot(x='Housing', y='Credit amount', data=df)
plt.title('Average Credit Amount by Housing Type')
plt.show()